### ISSUE TITLE
Keyword parameters are not working

### ISSUE THREAD

**Issue by Wiguwbe** [rainwoodman/tinypy#14]
Keyworded parameters on function calls don't behave as expected:

given an example function:
`def foo(a=1): print(a)`

calling with keyword parameters: `foo(a=5)`
prints `R{a: 5}` instead of `5`

Workaround: don't use keyworded parameters

Compilation with `tpy` is affected by this bug. A fix/workaround is provided in my latest Pull Request

**Comment by rainwoodman** [comment]
This is fixed in #27.
