### ISSUE TITLE
Crazy autobuild

### ISSUE THREAD

**Issue by turbocat2001** [rainwoodman/tinypy#20]
Using python to build is somehow abnormal.  Maybe it's worth using "Make".

**Comment by rainwoodman** [comment]
We already use make. 

However, the makefile has a python dependency. 
`make` calls the system python to run the tinypy.compiler package to compile the .py files of the tinypy.compiler to bytecode for embedding into tpy as a module.

**Comment by rofl0r** [comment]
> make calls the system python to run the tinypy.compiler package to compile the .py files of the tinypy.compiler to bytecode for embedding into tpy as a module.

do you think it's possible this could be done by tinypy itself ?
