### ISSUE TITLE
Probably type conversion

### ISSUE THREAD

**Issue by turbocat2001** [rainwoodman/tinypy#21]
I remember there was a bug in the old TinyPy.  For the x86 platform, for unknown reasons, the arguments were not read correctly.  For example, the function I my_func (0xffffffff) in TynyPy returned the value 0x7ffffff.  Although if you collect for x64, then everything is fine: the values ​​are the same.  5 days looking for a problem in the source code - so I did not find it.  Do you know anything about this?

**Comment by rainwoodman** [comment]
I think the old tinypy all numerical values (include integer types) was represented by a float. This may cause some issues casting between system int to and from a TP_NUM object.

The current version uses a double for TP_NUM. And we really should add support to a real, lossless integer type.

**Comment by turbocat2001** [comment]
Thanks for the answer.  Does this mean that you also have this bug?
