### ISSUE TITLE
Сompilation problem for 32 bit platform

### ISSUE THREAD

**Issue by turbocat2001** [rainwoodman/tinypy#33]
tinypy/tp_internal.h:11:27: error: enumerator value for 'static_assert_1' is not an integer constant

**Comment by rainwoodman** [comment]
The error itself could be a compiler incompatibility issue.
The static checks in the file asserts that the size of tp_obj is 24 bytes, which is only true on 64bit pointer platforms.

How urgent do you think it is to support 32 bit platforms?
If we want to add 32bit support, do you have a recommendation on how to set up a cross compilation toolchain (and test cases?)

**Comment by turbocat2001** [comment]
It looks like a regression anyway, since the old tinypy compiled under x32 without issue.

**Comment by rainwoodman** [comment]
It is. I was hoping to get away with only support 64bit and avoid maintaining conditionals for 32 bit. 
I just looked up that Raspberry PI is 32 bit only as of now (64bit is still being baked). So may be we cannot get away with 64bit only after all. Would it be fair to say 32bit support is a must until Raspberry PI drops 32bit?

I may be able to bring it back with minimal efforts (probably need to massage some of the unions). I do want to be able to run the test suites on an x32 system (e.g. with qemu?) to ensure some level of test coverage. I don't know if github actions allow setuping up an x32 SUT; it seems to only support docker images. Perhaps booting a qemu machine? How do you test on x32?

**Comment by turbocat2001** [comment]
Don't 32 bit programs work on 64 bit platforms?
The point is that I am porting your TinyPy for KolibriOS. We have a very old port on SVN with a bunch of bugs. I really hope that you will fix the assembly for x32. Python in KolibriOS is in your hands :)

**Comment by rainwoodman** [comment]
Sure. I see the need. I'll fiddle with this next week. 

It used to be that we need to install the .i386 packages, which may not be feasible on the github workflow action workers.
I'll look into setting up cross compilation and testing on an x32 linux inside qemu. I think doing so would help scaling to more platforms in the longer term.

**Comment by turbocat2001** [comment]
Thank you. I temporarily commented out the macro. But I will still wait for your build fix.

**Comment by rofl0r** [comment]
note that x32 != i386 - x32 is a separate ABI that uses 64bit registers but 32bit pointers (long = 4bytes). it uses __ILP32__ preprocessor macro for detection.

static assert can be written portably as 

```c
/* gives compile error if sizeof(long) is not 8 */
int arr[sizeof(long) == 8 ? 1 : -1];
```

**Comment by rainwoodman** [comment]
So the issue really is just the static assert is non portable (I got it from stackoverflow, I think)?

Could you share the compiler and commandline you are using?

**Comment by rainwoodman** [comment]
And I am not sure if I can find a real x32 (I thought it was i386) linux build for running the testing. I guess we can add CI with  KolibriOS after you are done with the port to ensure coverage.

**Comment by rofl0r** [comment]
> And I am not sure if I can find a real x32 (I thought it was i386)

i'm pretty sure turbocat didn't know the difference and used the term ignorantly (afaik windows uses the term x64 instead of x86_64 or amd64, which leads some people to think x32 would be the equivalent for 32bit), meaning i386 in reality. but if you want to test x32 afaik only gentoo and sabotage linux (my distro) support it.

**Comment by pfalcon** [comment]
> but if you want to test x32 afaik only gentoo and sabotage linux (my distro) support it.

Depends on what you mean by "support". On Ubuntu 18.04 it's:

```
$ apt list | grep x32 | wc
    558    1711   53895
$ apt list | wc
  69922  212763 3953313
 ```

I.e. only ~500 out of ~70000 packages have x32 support (and there's no separate "x32" arch, like Debian). But my [Pycopy](https://github.com/pfalcon/pycopy) Python dialect builds and runs perfectly well with it (given that x32 is just a "personality" of x86_64). It's actually pretty neat for JIT experiments, e.g. I run https://github.com/pfalcon/pycopy-jitgen mostly with the x32 build now, as x86_64 is gawdawful 64-bit bloat, and i386 is gawdawful CISC ABI.

**Comment by rainwoodman** [comment]
@pfalcon, does the guide at https://www.geeksforgeeks.org/compile-32-bit-program-64-bit-gcc-c-c/ look reasonable to you for a x32 setup?

The current code base uses long, intptr_t, and int64_t interchangeably. Some work is needed to clean this up -- even on a x32 system I suspect we still want TP_NUMBER to be double internally, which means we probably still want to pad the size of tp_obj to 24 bytes.

**Comment by rofl0r** [comment]
> does the guide at https://www.geeksforgeeks.org/compile-32-bit-program-64-bit-gcc-c-c/ look reasonable to you for a x32 setup?

my recommendation would be to use https://github.com/richfelker/musl-cross-make with `TARGET = x86_64-linux-muslx32` to build your own cross-compiler toolchain.

**Comment by rainwoodman** [comment]
Thanks -- but I'll still need a way to run the compiled artifacts -- I think it can be on qemu -- is there a 'hub' where we can find precompiled, potentially docker-like qemu images for different architectures?

**Comment by rainwoodman** [comment]
#39 adds a -m32 test and a -mx32 test. The source code seems to work as is as long as the sizeof(tp_obj) == 24 check is removed.

**Comment by rofl0r** [comment]
kernels built for x86_64 support x32 binaries if the config option CONFIG_X86_X32 was set.

you can check whether that's the case via

```
$ zcat /proc/config.gz | grep X32
CONFIG_X86_X32=y
```

**Comment by pfalcon** [comment]
> @pfalcon, does the guide at https://www.geeksforgeeks.org/compile-32-bit-program-64-bit-gcc-c-c/ look reasonable to you for a x32 setup?

As you seem to have already figured, you can build x32 binary with -mx32 gcc switch, and to run them, just have a few packages installed. And of course, have kernel built with support for it, @rofl0r points out. (Which standard Ubuntu kernels are, and I hope microsoft azure kernels also are.)

**Comment by rainwoodman** [comment]
Yes. The tests on github workflows now cover -mx32 and -m32. Let's hope this coverage is good enough and we don't need to cover endianness anytime soon..

**Comment by rainwoodman** [comment]
Closing the issue. Thanks everyone for the help!
