### ISSUE TITLE
Incorrect handling of text files.

### ISSUE THREAD

**Issue by turbocat2001** [rainwoodman/tinypy#35]
TinyPy crashes with error if the file was created in notepad.exe or some other test editors. Most likely related to '\ n' and '\ r'.

[test.txt](https://github.com/rainwoodman/tinypy/files/5795526/test.txt)

File "tinypy/compiler/py2bc.py", line 7, in compile
     tokens = tokenize.tokenize(s)
File "tinypy/compiler/tokenize.py", line 56, in tokenize
         u_error('tokenize',s,T.f)
File "tinypy/compiler/tokenize.py", line 25, in u_error
     raise Exception('error: '+ctx+'\n'+r)

**Comment by rainwoodman** [comment]
I'd prefer to run the script via dos2unix rather than add the logic to the compiler to parse both styles of line-ends.

That being said it appears that we already have a transform stage in tokenize.py::clean where we replace `\r\n` to `\n`.

**Comment by rainwoodman** [comment]
It's a bug in tpy_str_replace.

**Comment by rainwoodman** [comment]
@tubocat2001: Could you confirm if PR #37 fixes this?

**Comment by mxlgv** [comment]
@rainwoodman, 
You really fixed that! I am glad!
